<a href="https://colab.research.google.com/github/marmutapp/public/blob/main/Learning_Neural_Networks_From_Scratch_With_Some_Math%E2%80%8A_%E2%80%8APart_A_Python_%26%C2%A0Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Dependencies to be used later
import numpy as np
import random as rd
import time

In [13]:
# Input Data preparation
X1 = rd.sample(range(1, 500), 100)# Creates a list of 100 random numbers in the range of 1, 500
print("number of clicks on your website:\n",X1)
X2 = rd.sample(range(1, 500), 100)
print("\nnumber of people entering a mall:\n",X2)
x_input = np.array(list(map(lambda m,n:[m,n],X1,X2)))
print("\nnumber of clicks on your website, people entering a mall:\n", x_input)

number of clicks on your website:
 [346, 329, 356, 3, 391, 78, 47, 179, 191, 379, 100, 190, 492, 316, 493, 76, 345, 237, 437, 213, 489, 287, 454, 52, 141, 408, 169, 77, 224, 423, 243, 361, 152, 133, 479, 235, 80, 246, 499, 424, 85, 426, 376, 451, 211, 417, 338, 387, 114, 122, 309, 258, 83, 340, 272, 233, 33, 314, 158, 119, 229, 321, 210, 431, 2, 399, 369, 465, 466, 304, 332, 227, 308, 406, 430, 295, 90, 96, 231, 218, 105, 315, 171, 298, 173, 128, 409, 352, 487, 28, 400, 66, 67, 87, 393, 195, 54, 342, 160, 357]

number of people entering a mall:
 [157, 334, 22, 441, 41, 478, 494, 103, 483, 244, 432, 491, 378, 238, 38, 306, 425, 52, 127, 264, 147, 372, 328, 217, 174, 272, 443, 250, 498, 475, 354, 196, 424, 496, 495, 228, 465, 2, 207, 400, 270, 68, 256, 58, 105, 218, 198, 88, 56, 457, 184, 213, 317, 79, 452, 254, 412, 66, 43, 466, 136, 385, 462, 363, 160, 419, 135, 208, 170, 120, 454, 240, 107, 77, 467, 230, 8, 25, 44, 485, 14, 51, 342, 231, 39, 102, 242, 381, 415, 156, 341, 410, 330, 235

In [14]:
# Output Data preparation
y_output = np.array(list(map(lambda m:sum(m),x_input))) # Try experimenting with this function and model parameters. For egs. np.array(list(map(lambda m:sum(m)**2,x_input)))
y_output = y_output.reshape(np.shape(y_output)[0],1)
print("\nThis is the output variable which reflects the number of purchases on each of the 10 days:\n",y_output)


This is the output variable which reflects the number of purchases on each of the 10 days:
 [[503]
 [663]
 [378]
 [444]
 [432]
 [556]
 [541]
 [282]
 [674]
 [623]
 [532]
 [681]
 [870]
 [554]
 [531]
 [382]
 [770]
 [289]
 [564]
 [477]
 [636]
 [659]
 [782]
 [269]
 [315]
 [680]
 [612]
 [327]
 [722]
 [898]
 [597]
 [557]
 [576]
 [629]
 [974]
 [463]
 [545]
 [248]
 [706]
 [824]
 [355]
 [494]
 [632]
 [509]
 [316]
 [635]
 [536]
 [475]
 [170]
 [579]
 [493]
 [471]
 [400]
 [419]
 [724]
 [487]
 [445]
 [380]
 [201]
 [585]
 [365]
 [706]
 [672]
 [794]
 [162]
 [818]
 [504]
 [673]
 [636]
 [424]
 [786]
 [467]
 [415]
 [483]
 [897]
 [525]
 [ 98]
 [121]
 [275]
 [703]
 [119]
 [366]
 [513]
 [529]
 [212]
 [230]
 [651]
 [733]
 [902]
 [184]
 [741]
 [476]
 [397]
 [322]
 [780]
 [452]
 [424]
 [632]
 [274]
 [787]]


In [15]:
# Data Scaling - basically normalizing all data values between 0 & 1
def linear_downscaling(dataset, min=None, max=None):
  if max == None or min == None:
    max = np.max(dataset)
    min = np.min(dataset)
  scaled_down_value = np.array(list(map(lambda x: (x-min)/(max-min), dataset)))
  if scaled_down_value.ndim==1:# If it is a one-dimensional array, this will convert it into two dimensional array i.e. (20,) shape becomes (20,1)
    scaled_down_value = scaled_down_value.reshape(np.shape(scaled_down_value)[0],1)
  return scaled_down_value, min, max# Return min, max aling with scaled value in order to re-scale later

def linear_upscaling(dataset, min, max):
  return np.array(list(map(lambda x: x*(max-min)+min, dataset)))

x_input_0, x_input_min_0, x_input_max_0  = linear_downscaling(x_input[:,0])
x_input_1, x_input_min_1, x_input_max_1  = linear_downscaling(x_input[:,1])
x_input = np.array(list(map(lambda m,n:[m[0],n[0]],x_input_0,x_input_1)))
y_output, y_output_min, y_output_max  = linear_downscaling(y_output)

In [ ]:
# Example activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))#Element-wise operation

In [16]:
# Model shape
layer_size_1=3
x_input_shape=np.shape(x_input)

# Initializing weights & bias to some random values and zeroes respectively
weights_1=np.random.randn(x_input_shape[1],layer_size_1)
bias_1=np.zeros((1,layer_size_1))

# Multiplying weights with 1st input value and adding bias
# We're just doing this for the first input X[0:1]
z_layer_1 = np.dot(x_input[0:1], weights_1) + bias_1

# Applying the activation function right after
a_layer_1 = sigmoid(z_layer_1)

In [17]:
# Let's do this again.. for another layer
# In this case, the output from previous layer becomes our input
# Model shape
layer_size_2=3
a_layer_1_shape=np.shape(a_layer_1)

# Initializing weights & bias to some random values and zeroes respectively
weights_2=np.random.randn(a_layer_1_shape[1],layer_size_2)
bias_2=np.zeros((1,layer_size_2))

# Multiplying weights with 1st input value and adding bias
z_layer_2 = np.dot(a_layer_1, weights_2) + bias_2

# Applying the activation function right after
a_layer_2 = sigmoid(z_layer_2)

In [18]:
# Converging this to our output value
# Last layer is just going to have the shape of our actual output values i.e. Y as it is what we are trying to predict
# Model shape
Y_layer_size=1#layer_size_3 basically
a_layer_2_shape=np.shape(a_layer_2)

# Initializing weights & bias to some random values and zeroes respectively
weights_3=np.random.randn(a_layer_2_shape[1],Y_layer_size)
bias_3=np.zeros((1,Y_layer_size))

# Multiplying weights with 1st input value and adding bias
z_layer_3 = np.dot(a_layer_2, weights_3) + bias_3

# Applying the activation function right after
y_generated = sigmoid(z_layer_3)#same as a_layer_3
print("Predicted y_generated given weights & biases:", y_generated,"\n")

Predicted y_generated given weights & biases: [[0.60550315]] 



In [ ]:
# Error function
# Standard Mean Square Error
def mse(x,y):
  #return np.array(list(np.power(x-y,2)/np.shape(x)[0]))
  return np.power(x-y,2)/np.shape(x)[0]

In [ ]:
# Error function 1st order derivative
def mse_prime(x,y):
  return (x - y)

In [ ]:
# Activation functions & their derivatives
def linear(x):
  return x

def linear_prime(x):
  return 1

def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_prime(x):
  return sigmoid(x)*(1-sigmoid(x))

def relu(x):
    return np.maximum(0, x)

def relu_prime(x):
    return np.where(x > 0, 1, 0)

def tanh(x):
  return np.tanh(x)

def tanh_prime(x):
  return 1 - np.tanh(x)**2

In [19]:
error_3 = mse(y_output[0:1], y_generated)# Generalized version is mse(y_output[batch*batch_size:(batch+1)*batch_size], y_generated)
print("Error between actual Y output & our predicted Y output:", error_3,"\n")

Error between actual Y output & our predicted Y output: [[0.0204989]] 



In [20]:
# Backpropagation
learning_rate = 0.1

error_3_prime = mse_prime(y_generated, y_output[0:1])
error_2_prime = np.dot(error_3_prime,weights_3.T) * sigmoid_prime(z_layer_2)
error_1_prime = np.dot(error_2_prime,weights_2.T) * sigmoid_prime(z_layer_1)

weights_error_3 = np.dot(a_layer_2.T, error_3_prime)
bias_error_3 = error_3_prime
weights_error_2 = np.dot(a_layer_1.T, error_2_prime)
bias_error_2 = error_2_prime
weights_error_1 = np.dot(np.array(x_input)[0:1].T, error_1_prime)
bias_error_1 = error_1_prime

weights_3 = weights_3 - weights_error_3*learning_rate
bias_3 = bias_3 - bias_error_3*learning_rate
weights_2 = weights_2 - weights_error_2*learning_rate
bias_2 = bias_2 - bias_error_2*learning_rate
weights_1 = weights_1 - weights_error_1*learning_rate
bias_1 = bias_1 - bias_error_1*learning_rate

# We now have the weights & biases updated
# We can use forward pass to get new y_generated

In [ ]:
# FULL MODEL WITH FORWARD PASS + BACKPROPAGATION IN LOOP

#Clubbing all parameters before loop

#Defining layer size or number of neurons for each layer
layer_size_1=3
layer_size_2=3
Y_layer_size=1#layer_size_3 basically

# Model parameters
batch_size = 16
epochs = 20000
learning_rate = 0.05

# Initializing weights & bias to some random values and zeroes respectively
x_input_shape=np.shape(x_input)
weights_1=np.random.randn(x_input_shape[1],layer_size_1)
bias_1=np.zeros((batch_size,layer_size_1))

a_layer_1_shape=[batch_size,layer_size_1]
weights_2=np.random.randn(a_layer_1_shape[1],layer_size_2)
bias_2=np.zeros((batch_size,layer_size_2))

a_layer_2_shape=[batch_size,layer_size_2]
weights_3=np.random.randn(a_layer_2_shape[1],Y_layer_size)
bias_3=np.zeros((batch_size,Y_layer_size))

# The loop for running the neural network
for i in range(0,epochs):
  start_time=time.time()
  for batch in range(0,int(x_input_shape[0]/batch_size)):
    # Forward Pass

    # Multiplying weights with 1st input value and adding bias and applying the activation function right after for each layer
    z_layer_1 = np.dot(x_input[batch*batch_size:(batch+1)*batch_size], weights_1) + bias_1
    a_layer_1 = sigmoid(z_layer_1)
    z_layer_2 = np.dot(a_layer_1, weights_2) + bias_2
    a_layer_2 = sigmoid(z_layer_2)
    z_layer_3 = np.dot(a_layer_2, weights_3) + bias_3
    y_generated = linear(z_layer_3)#same as a_layer_3 & linear(z_layer_3) function can be replaced with just z_layer_3

    error_3 = mse(y_output[batch*batch_size:(batch+1)*batch_size], y_generated)

    # Backpropagation
    error_3_prime = mse_prime(y_generated, y_output[batch*batch_size:(batch+1)*batch_size]) * linear_prime(z_layer_3)# linear_prime is just 1 & can be removed entirely
    error_2_prime = np.dot(error_3_prime, weights_3.T) * sigmoid_prime(z_layer_2)
    error_1_prime = np.dot(error_2_prime, weights_2.T) * sigmoid_prime(z_layer_1)

    weights_error_3 = np.dot(a_layer_2.T, error_3_prime)
    bias_error_3 = error_3_prime
    weights_error_2 = np.dot(a_layer_1.T, error_2_prime)
    bias_error_2 = error_2_prime
    weights_error_1 = np.dot(x_input[batch*batch_size:(batch+1)*batch_size].T, error_1_prime)
    bias_error_1 = error_1_prime

    weights_3 = weights_3 - weights_error_3*learning_rate
    bias_3 = bias_3 - bias_error_3*learning_rate
    weights_2 = weights_2 - weights_error_2*learning_rate
    bias_2 = bias_2 - bias_error_2*learning_rate
    weights_1 = weights_1 - weights_error_1*learning_rate
    bias_1 = bias_1 - bias_error_1*learning_rate

  try:
    if i%int(epochs*0.1)==0 : print("\nepoch:",i,"\terror: ",sum(error_3)[0],"\t average time per epoch: %.5f ms" %((time.time()-start_time)*1000/batch_size))
  except ZeroDivisionError:
    print("\nepoch:",i,"\terror_3:",sum(error_3))


epoch: 0 	error:  0.032570203360272464 	 average time per epoch: 0.42453 ms

epoch: 2000 	error:  1.167400742069551e-05 	 average time per epoch: 0.02950 ms

epoch: 4000 	error:  7.553810686555276e-06 	 average time per epoch: 0.02983 ms

epoch: 6000 	error:  6.196504341356965e-06 	 average time per epoch: 0.03049 ms

epoch: 8000 	error:  5.345148603218313e-06 	 average time per epoch: 0.06723 ms

epoch: 10000 	error:  4.7227197009112164e-06 	 average time per epoch: 0.03077 ms

epoch: 12000 	error:  4.2439496306279944e-06 	 average time per epoch: 0.03085 ms

epoch: 14000 	error:  3.865126794450179e-06 	 average time per epoch: 0.03029 ms

epoch: 16000 	error:  3.558894044565183e-06 	 average time per epoch: 0.02965 ms

epoch: 18000 	error:  3.306755201515024e-06 	 average time per epoch: 0.03025 ms


In [ ]:
# Test your neural network if it can predict well after its "learning" process
# Let's generate a few test points in the same range
new_x_input_1 = np.array(rd.sample(range(1, 500), batch_size*2))
new_x_input_2 = np.array(rd.sample(range(1, 500), batch_size*2))
new_x_input = np.array(list(map(lambda m,n:[m,n],new_x_input_1,new_x_input_2)))
print("Here are our input values to predict the output for: \n", new_x_input)
# Scale the inputs using input scaling factor
new_x_input_0, _, _  = linear_downscaling(new_x_input[:,0], x_input_min_0, x_input_max_0)
new_x_input_1, _, _  = linear_downscaling(new_x_input[:,1], x_input_min_1, x_input_max_1)
new_x_input = np.array(list(map(lambda m,n:[m[0],n[0]],new_x_input_0,new_x_input_1)))
print("Here are our scaled down input values to predict the output for: \n", new_x_input)
# These are the same variables & structure that we used in the forward pass to get y_generated for new input
# When you train, the shape of your internal or hidden layers are fixed as per your batch_size so your test input should also adhere to the batch_size constraint
print("Here are the corresponding predictions for output values:\n")
for batch in range(int(np.shape(new_x_input)[0]/batch_size)):
  z_layer_1 = np.dot(new_x_input[batch*batch_size:(batch+1)*batch_size], weights_1)   + bias_1
  a_layer_1 = sigmoid(z_layer_1)

  z_layer_2 = np.dot(a_layer_1, weights_2) + bias_2
  a_layer_2 = sigmoid(z_layer_2)

  z_layer_3 = np.dot(a_layer_2, weights_3) + bias_3
  y_predicted = linear(z_layer_3)#same as a_layer_3

  print(linear_upscaling(y_predicted, y_output_min, y_output_max))# y_generated values are downscaled as our training y_output data was also downscaled; We need to upscale it back to get output value as per original levels

Here are our input values to predict the output for: 
 [[394  68]
 [271 422]
 [456 115]
 [ 15  72]
 [482 431]
 [314 421]
 [200  94]
 [196 429]
 [357 257]
 [186  13]
 [ 74 152]
 [438 424]
 [155 349]
 [134 282]
 [492 123]
 [483 133]
 [307 465]
 [ 44 397]
 [471 416]
 [ 60 425]
 [236 220]
 [429 109]
 [ 99 439]
 [ 51 226]
 [266 388]
 [125 344]
 [484 430]
 [389   5]
 [ 96 482]
 [215 347]
 [120  25]
 [399   7]]
Here are our scaled down input values to predict the output for: 
 [[ 0.79233871  0.12678937]
 [ 0.54435484  0.85071575]
 [ 0.91733871  0.22290389]
 [ 0.02822581  0.13496933]
 [ 0.96975806  0.86912065]
 [ 0.63104839  0.84867076]
 [ 0.40120968  0.1799591 ]
 [ 0.39314516  0.86503067]
 [ 0.71774194  0.51329243]
 [ 0.37298387  0.01431493]
 [ 0.14717742  0.29856851]
 [ 0.88104839  0.85480573]
 [ 0.31048387  0.70143149]
 [ 0.26814516  0.56441718]
 [ 0.98991935  0.2392638 ]
 [ 0.97177419  0.2597137 ]
 [ 0.61693548  0.93865031]
 [ 0.08669355  0.799591  ]
 [ 0.94758065  0.83844581]
 [ 0.1189516

In [ ]:
actual_y_new_output = linear_upscaling(new_x_input[:,0], x_input_min_0, x_input_max_0) + linear_upscaling(new_x_input[:,1], x_input_min_1, x_input_max_1 )# With alternative dataset option of y function -- (linear_upscaling(new_x_input[:,0], x_input_min_0, x_input_max_0) + linear_upscaling(new_x_input[:,1], x_input_min_1, x_input_max_1 ))**2
print("\nHere are the actual values based on what we already know the relationship to be:\n", actual_y_new_output)


Here are the actual values based on what we already know the relationship to be:
 [462. 693. 571.  87. 913. 735. 294. 625. 614. 199. 226. 862. 504. 416.
 615. 616. 772. 441. 887. 485. 456. 538. 538. 277. 654. 469. 914. 394.
 578. 562. 145. 406.]
